FROM golang:1.15-buster AS build

# Install prerequisites.
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    cmake \
    curl \
    git \
    libcurl3-dev \
    libleptonica-dev \
    liblog4cplus-dev \
    libopencv-dev \
    libtesseract-dev \
    wget

# Clone openalpr.
RUN git clone https://github.com/openalpr/openalpr /openalpr

# Setup the build directory.
run mkdir /openalpr/src/build
workdir /openalpr/src/build

# Compile.
RUN cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc .. && \
    make -j2 && \
    make install

ENV GO111MODULE=on

RUN mkdir -p /usr/local/share/openalpr/
RUN cp -R /usr/share/openalpr/runtime_data /usr/local/share/openalpr/runtime_data
