[log]
level = "debug"
mode = "dev"

[openalpr]
max_number = 100
country = "ua"
config_file = "/usr/share/openalpr/config/openalpr.defaults.conf"
runtime_dir = "/usr/share/openalpr/runtime_data"

[server]
shutdown_timeout = "15s"
read_timeout = "10s"
write_timeout = "10s"
idle_timeout = "10s"

[s3]
endpoint = "ams3.digitaloceanspaces.com"
access_key_id = "xxx"
secret_access_key = "xxx"
ssl = true
bucket = "open-cars"
