[log]
level = "debug"
mode  = "dev"

[openalpr]
max_number  = 5
country     = "ua"
config_file = "/usr/share/openalpr/config/openalpr.defaults.conf"
runtime_dir = "/usr/share/openalpr/runtime_data"

[server]
shutdown_timeout = "30s"
read_timeout     = "10s"
write_timeout    = "10s"
idle_timeout     = "10s"